kind: pipeline
name: vasques

workspace:
  base: /go
  path: src/github.com/scbizu/vasques

steps:
  - name: build
    image: golang:1.14
    environment:
      GO111MODULE: on
    commands:
    - go install

- name: test
  image: golang:1.14
  environment:
    GO111MODULE: on
  commands:
    - go test ./...
